### ISSUE TITLE
Week calendar skewed( version .2.2.2)

### ISSUE THREAD

**Issue by KurtSmith** [Serhioromano/bootstrap-calendar#224]
I noticed that the version on the demo site has 

``` css
.cal-week-box {
  position: relative;
}
```

where as the version I have doesn't.

If i use the demo version it looks right.

![image](https://f.cloud.github.com/assets/6589669/2082474/9f680602-8df0-11e3-9662-20399de7d34f.png)
